name: CC的SSL状态

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 16 * * *' 

jobs:
  CheckSSL:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: master
    - name: Setup node
      uses: actions/setup-node@main
      with:
        node-version: '15.x'
    - name: Cache node modules
      uses: actions/cache@main
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install & Build
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        npm i
        git clone https://github.com/ChenYFan/CheckSSL --depth=2
        npm run build
        cd CheckSSL
        chmod +x checker.sh
        ./checker.sh blog.ccknbc.cc ccknbc.cc www.ccknbc.cc nav.ccknbc.cc tcb.ccknbc.cc img.ccknbc.cc cc.instatus.com ccknbc.statuspage.io ccknbc.freshstatus.io status.ccknbc.ml ssl.ccknbc.cc waline.ccknbc.ml
        cp -rf ./output/ct.json ../public/ct.json
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./public
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Updated By Github Actions'
